server:
  port: 8084
spring:
  application:
    name: area-service
  datasource:
    url: jdbc:mysql://192.168.25.129:3306/anntly?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&useAffectedRows=true&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    status-page-url:
      http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #开启驼峰
  mapper-locations: classpath:mapper/*.xml

#security:
#  oauth2:
#    client:
#      access-token-uri: http://127.0.0.1:7777/uaa/oauth/token #令牌端点
#      user-authorization-uri: http://127.0.0.1:7777/uaa/oauth/authorize #授权端点
#      client-id: area_server #OAuth2客户端ID
#      client-secret: areasecret #OAuth2客户端密钥
