server:
  port: 10010
spring:
  application:
    name: api-gateway
  redis:
    host: 192.168.25.129
    port: 6379
    password: anntly
    jedis:
      pool:
        max-active: 3
        max-idle: 3
        min-idle: 1
        max-wait: -1 # 连接池最大等待时间 -1表示没有限制
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    dish-service: /dish/** # 将菜品微服务映射到 /dish/**
    shop-service: /shop/** # 将餐厅微服务映射到 /shop/**
    user-service: /user/** # 用户微服务
    auth-service: /auth/** # 授权中心微服务
    area-service:
      path: /area/**
      serviceId: area-service
      strip-prefix: false  #去掉前缀 访问area/...
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false  #去掉前缀 访问upload/...
  add-host-header: true # 携带请求本身的head头信息
  sensitive-headers: # 配置禁止使用的头信息，这里设置为null，否则set-cookie无效
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 8000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 15000 # 熔断超时时长：10000ms
