server:
  port: 8083
spring:
  application:
    name: shop-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.25.129:3306/anntly?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&useAffectedRows=true&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    status-page-url:
      http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #开启驼峰
  mapper-locations: classpath:mapper/*.xml
